/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gdr.dragonball;

import javax.swing.*;
import java.awt.event.ActionEvent;
/**
 *
 * @author grottelli.gabriele
 */

public class SceltaPersonaggio extends javax.swing.JFrame { 
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SceltaPersonaggio.class.getName());
    private JButton[] bottoniPersonaggi; 
    private Personaggio personaggioSelezionato; 
    
    private String[] tuttiNomi = {
        "goku_ragazzo", "goku_adulto", "goku_gt", "goku_ultra_istinto", 
        "vegeta_scouter", "vegeta_majin", "baby_vegeta", "vegeta_ultra_ego",
        "gohan_bambino", "gohan_ragazzo", "gohan_mystic", "gohan_beast",
        "trunks_futuro", "trunks_bambino", "xeno_trunks",
        "vegito", "gogeta", "gotenks",
        "freezer", "cooler", "metal_cooler", "broly_anni_90", 
        "broly_super_saiyan_della_leggenda", "janemba", "hildegarn", "cell_max",
        "beerus", "whis", "jiren", "goku_black", "zamasu", "hit",
        "crilin", "yamcha", "tenshinhan", "maestro_muten", "arale",
        "syn_shenron", "syn_shenron_omega", "uub",
        "moro", "granolah", "gas"
    };

    private int indicePagina = 0; 
    private final int BOTTONI_PER_PAGINA = 6;

    public SceltaPersonaggio() {
        initComponents(); 
        
        bottoniPersonaggi = new JButton[]{jButton1, jButton2, jButton3, jButton4, jButton5, jButton6};
        
        btnAvvia.setVisible(false);

        for (JButton btn : bottoniPersonaggi) {
            btn.addActionListener(e -> {
                selezionaPersonaggio(btn.getText());
            });
        }

        aggiornaBottoni();
        
        setSize(1000, 400);
        setLocationRelativeTo(null);
    }

    private void aggiornaBottoni() {
        for (int i = 0; i < BOTTONI_PER_PAGINA; i++) {
            int indiceReale = indicePagina + i;

            if (indiceReale < tuttiNomi.length) {
                String nomeID = tuttiNomi[indiceReale];
                
                bottoniPersonaggi[i].setText(nomeID.replace("_", " "));
                bottoniPersonaggi[i].setVisible(true);
            } else {
                bottoniPersonaggi[i].setVisible(false);
            }
        }   

        btnIndietro.setEnabled(indicePagina > 0);
        btnAvanti.setEnabled(indicePagina + BOTTONI_PER_PAGINA < tuttiNomi.length);
    }

    private void selezionaPersonaggio(String nomeVisibile) {
        String nomeID = nomeVisibile.toLowerCase().replace(" ", "_");
        
        personaggioSelezionato = new Personaggio(nomeID);
        
        btnAvvia.setText("Avvia con " + nomeVisibile);
        btnAvvia.setVisible(true);
        
        System.out.println("DEBUG: Selezionato " + nomeID);
    }

    private void avviaGioco() {
    if (personaggioSelezionato != null) {

        int indiceRandomNemico = (int) (Math.random() * tuttiNomi.length);
        String nomeNemicoCasuale = tuttiNomi[indiceRandomNemico];
        Personaggio nemico = new Personaggio(nomeNemicoCasuale);

        String[] mappeDisponibili = {"Pianeta Namecc", "Torneo Tenkaichi", "Stanza dello Spirito e del Tempo", "Città dell'Ovest"};
        int indiceMappa = (int) (Math.random() * mappeDisponibili.length);
        Mappa mappaCasuale = new Mappa(mappeDisponibili[indiceMappa]);

        Difficoltà[] diffs = Difficoltà.values();
        Difficoltà difficoltaCasuale = diffs[(int) (Math.random() * diffs.length)];

        SchermataDiCombattimento combat = new SchermataDiCombattimento(
            personaggioSelezionato, 
            nemico, 
            mappaCasuale, 
            difficoltaCasuale
        );
        
        combat.setVisible(true);
        this.dispose();
        
    } else {
        JOptionPane.showMessageDialog(this, "Seleziona un personaggio prima di continuare!");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnIndietro = new javax.swing.JButton();
        btnAvanti = new javax.swing.JButton();
        btnAvvia = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 140, 130, 23);

        jButton2.setText("jButton2");
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 140, 140, 23);

        jButton3.setText("jButton3");
        getContentPane().add(jButton3);
        jButton3.setBounds(340, 140, 130, 23);

        jButton4.setText("jButton4");
        getContentPane().add(jButton4);
        jButton4.setBounds(500, 140, 150, 23);

        jButton5.setText("jButton5");
        getContentPane().add(jButton5);
        jButton5.setBounds(700, 140, 150, 23);

        jButton6.setText("jButton6");
        getContentPane().add(jButton6);
        jButton6.setBounds(890, 140, 150, 23);

        btnIndietro.setText("Indietro");
        btnIndietro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndietroActionPerformed(evt);
            }
        });
        getContentPane().add(btnIndietro);
        btnIndietro.setBounds(289, 245, 72, 23);

        btnAvanti.setText("Avanti");
        btnAvanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvantiActionPerformed(evt);
            }
        });
        getContentPane().add(btnAvanti);
        btnAvanti.setBounds(530, 250, 72, 23);

        btnAvvia.setText("Avvia");
        btnAvvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvviaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAvvia);
        btnAvvia.setBounds(750, 250, 72, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvantiActionPerformed
        indicePagina += BOTTONI_PER_PAGINA;
        aggiornaBottoni();
    }//GEN-LAST:event_btnAvantiActionPerformed

    private void btnIndietroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndietroActionPerformed
        indicePagina -= BOTTONI_PER_PAGINA;
        if (indicePagina < 0) indicePagina = 0;
        aggiornaBottoni();
    }//GEN-LAST:event_btnIndietroActionPerformed

    private void btnAvviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvviaActionPerformed
        avviaGioco();
    }//GEN-LAST:event_btnAvviaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SceltaPersonaggio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvanti;
    private javax.swing.JButton btnAvvia;
    private javax.swing.JButton btnIndietro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
