/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gdr.dragonball;

import javax.swing.*;
/**
 *
 * @author grottelli.gabriele
 */
public class schermataMondo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(schermataMondo.class.getName());
    private Personaggio eroe;
    private Inventario mioInventario = new Inventario();
    private boolean nemicoPresente = false;

    public schermataMondo(Personaggio p) {
        this.eroe = p;
        initComponents();

        caricaImmaginePersonaggio();

        btnCombatti.setVisible(false);
        btnNonCombatti.setVisible(false);

        setSize(800, 600);
        setLocationRelativeTo(null);
    }

    private void caricaImmaginePersonaggio() {
        String nomeFile = eroe.nome.toLowerCase().replace(" ", "_").replace("(", "").replace(")", "");

        String path = "/gdr/dragonball/immagini/" + nomeFile + ".png";

        java.net.URL imgURL = getClass().getResource(path);

        if (imgURL != null) {
            ImageIcon icon = new ImageIcon(imgURL);

            int w = lblPersonaggio.getWidth();
            int h = lblPersonaggio.getHeight();

            java.awt.Image img = icon.getImage().getScaledInstance(w, h, java.awt.Image.SCALE_SMOOTH);

            lblPersonaggio.setIcon(new ImageIcon(img));
            lblPersonaggio.setText("");
        } else {
            lblPersonaggio.setText("Immagine non trovata");
        }
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInventario = new javax.swing.JButton();
        btnEsplora = new javax.swing.JButton();
        btnNonCombatti = new javax.swing.JButton();
        lblPersonaggio = new javax.swing.JLabel();
        btnCombatti = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnInventario.setText("Inventario");
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInventario);
        btnInventario.setBounds(20, 340, 90, 23);

        btnEsplora.setText("Esplora");
        btnEsplora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsploraActionPerformed(evt);
            }
        });
        getContentPane().add(btnEsplora);
        btnEsplora.setBounds(160, 340, 90, 23);

        btnNonCombatti.setText("Rifiuta");
        btnNonCombatti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNonCombattiActionPerformed(evt);
            }
        });
        getContentPane().add(btnNonCombatti);
        btnNonCombatti.setBounds(20, 410, 90, 23);

        lblPersonaggio.setText("jLabel1");
        getContentPane().add(lblPersonaggio);
        lblPersonaggio.setBounds(0, 0, 310, 280);

        btnCombatti.setText("Combatti");
        btnCombatti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCombattiActionPerformed(evt);
            }
        });
        getContentPane().add(btnCombatti);
        btnCombatti.setBounds(160, 410, 90, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(320, 10, 360, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNonCombattiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNonCombattiActionPerformed
        jTextArea1.append("Hai deciso di non combattere.\n");
        nemicoPresente = false;
        btnCombatti.setVisible(false);
        btnNonCombatti.setVisible(false);
        btnEsplora.setEnabled(true);
    }//GEN-LAST:event_btnNonCombattiActionPerformed

    private void btnCombattiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCombattiActionPerformed
        jTextArea1.append("Combatti!\n");
        Personaggio nemico = new Personaggio("goku_ragazzo");
        Mappa mappa = new Mappa("monte_paozu");
        SchermataDiCombattimento f = new SchermataDiCombattimento(eroe, nemico, mappa);
        f.setVisible(true);
        this.dispose();    
    }//GEN-LAST:event_btnCombattiActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        jTextArea1.append("--- APERTURA ZAINO ---\n");
        jTextArea1.append(mioInventario.mostraOggetti());
        jTextArea1.append("-----------------------\n");
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnEsploraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsploraActionPerformed
        if (nemicoPresente) {
            jTextArea1.append("C'è un nemico davanti a te! Devi decidere se combattere o rifiutare.\n");
            return;
        }

        double chance = Math.random();
    
        if (chance < 0.3) {
            String[] possibiliOggetti = {"Senzu", "Capsula Hoi-Poi", "Sfera del Drago (4 stelle)", "Tuta da combattimento"};
            String trovato = possibiliOggetti[(int)(Math.random() * possibiliOggetti.length)];
        
            mioInventario.aggiungiOggetto(trovato);
            jTextArea1.append("Hai trovato: " + trovato + "! Salvato nell'inventario.\n");
        
        } else if (chance < 0.7) {
            jTextArea1.append("ATTENZIONE! Un nemico ti sfida. Vuoi combattere?\n");
            nemicoPresente = true;
            btnCombatti.setEnabled(true);
            btnNonCombatti.setEnabled(true);
            btnCombatti.setVisible(true);
            btnNonCombatti.setVisible(true);
            btnEsplora.setEnabled(false); 
        
        } else {
            jTextArea1.append("Hai camminato a lungo, ma non hai trovato nulla.\n");
        }
    }//GEN-LAST:event_btnEsploraActionPerformed
//
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCombatti;
    private javax.swing.JButton btnEsplora;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnNonCombatti;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblPersonaggio;
    // End of variables declaration//GEN-END:variables
}
