/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gdr.dragonball;

/**
 *
 * @author grottelli.gabriele
 */
public class SchermataStart extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SchermataStart.class.getName());

    /**
     * Creates new form SchermataStart
     */
    public SchermataStart() {
        initComponents();
        setSize(800, 600);
        setLocationRelativeTo(null);
        setVisible(true);
        this.setUndecorated(true); 
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null); 
        
        btnCaricaPartita.setContentAreaFilled(false);
        btnStart.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStart = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCaricaPartita = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnStart.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        btnStart.setText("Inzia Il Gioco");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        getContentPane().add(btnStart);
        btnStart.setBounds(670, 370, 248, 49);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 2, 100)); // NOI18N
        jLabel1.setText("DRAGON BALL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(460, 60, 750, 140);

        btnCaricaPartita.setFont(new java.awt.Font("Segoe Script", 0, 20)); // NOI18N
        btnCaricaPartita.setText("Carica Partita");
        btnCaricaPartita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaricaPartitaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCaricaPartita);
        btnCaricaPartita.setBounds(690, 510, 200, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\grott\\Downloads\\Gemini_Generated_Image_wpvu3iwpvu3iwpvu.png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-20, 0, 1620, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        SceltaPersonaggio scelta = new SceltaPersonaggio();
        scelta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnCaricaPartitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaricaPartitaActionPerformed
        try {
            java.io.FileInputStream fileIn = new java.io.FileInputStream("salvataggio.dat");
            java.io.ObjectInputStream in = new java.io.ObjectInputStream(fileIn);
        
            Personaggio eroeCaricato = (Personaggio) in.readObject();
            Inventario inventarioCaricato = (Inventario) in.readObject();
        
            in.close();
            fileIn.close();
        
            schermataMondo mondo = new schermataMondo(eroeCaricato);
        
            mondo.setInventario(inventarioCaricato);
        
            mondo.setVisible(true);
            this.dispose();
        
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Errore nel caricamento: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCaricaPartitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SchermataStart().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaricaPartita;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
