/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gdr.dragonball;

/**
 *
 * @author grottelli.gabriele
 */
public class schermataMondo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(schermataMondo.class.getName());
    
    private Personaggio eroe;
    
    public schermataMondo(Personaggio p) {
        initComponents();
        this.eroe = p; 
        System.out.println("Il mondo è stato caricato con: " + eroe.nome);
        this.setUndecorated(true); 
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null); 
    }
    
    private Inventario mioInventario = new Inventario();
    
    private boolean nemicoPresente = false;
    
    /**
     * Creates new form SceltaMappa
     */
    public schermataMondo() {
        initComponents();
        btnCombatti.setVisible(false);
        btnNonCombatti.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInventario = new javax.swing.JButton();
        btnEsplora = new javax.swing.JButton();
        btnNonCombatti = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCombatti = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnInventario.setText("Inventario");
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInventario);
        btnInventario.setBounds(15, 240, 90, 23);

        btnEsplora.setText("Esplora");
        btnEsplora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsploraActionPerformed(evt);
            }
        });
        getContentPane().add(btnEsplora);
        btnEsplora.setBounds(145, 240, 90, 23);

        btnNonCombatti.setText("Rifiuta");
        btnNonCombatti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNonCombattiActionPerformed(evt);
            }
        });
        getContentPane().add(btnNonCombatti);
        btnNonCombatti.setBounds(15, 300, 90, 23);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 310, 200);

        btnCombatti.setText("Combatti");
        btnCombatti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCombattiActionPerformed(evt);
            }
        });
        getContentPane().add(btnCombatti);
        btnCombatti.setBounds(145, 300, 90, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(320, 20, 360, 190);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNonCombattiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNonCombattiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNonCombattiActionPerformed

    private void btnCombattiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCombattiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCombattiActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        jTextArea1.append("--- APERTURA ZAINO ---\n");
        jTextArea1.append(mioInventario.mostraOggetti());
        jTextArea1.append("-----------------------\n");
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnEsploraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsploraActionPerformed
        if (nemicoPresente) {
            jTextArea1.append("C'è un nemico davanti a te! Devi decidere se combattere o rifiutare.\n");
            return;
        }

        double chance = Math.random();
    
        if (chance < 0.3) {
            String[] possibiliOggetti = {"Senzu", "Capsula Hoi-Poi", "Sfera del Drago (4 stelle)", "Tuta da combattimento"};
            String trovato = possibiliOggetti[(int)(Math.random() * possibiliOggetti.length)];
        
            mioInventario.aggiungiOggetto(trovato);
            jTextArea1.append("Hai trovato: " + trovato + "! Salvato nell'inventario.\n");
        
        } else if (chance < 0.7) {
            jTextArea1.append("ATTENZIONE! Un nemico ti sfida. Vuoi combattere?\n");
            nemicoPresente = true;
            btnCombatti.setEnabled(true);
            btnNonCombatti.setEnabled(true);
            btnCombatti.setVisible(true);
            btnNonCombatti.setVisible(true);
            btnEsplora.setEnabled(false); 
        
        } else {
            jTextArea1.append("Hai camminato a lungo, ma non hai trovato nulla.\n");
        }
    }//GEN-LAST:event_btnEsploraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new schermataMondo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCombatti;
    private javax.swing.JButton btnEsplora;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnNonCombatti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
