/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gdr.dragonball;

/**
 *
 * @author grottelli.gabriele
 */
public class SchermataDiCombattimento extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SchermataDiCombattimento.class.getName());

    /**
     * Creates new form SchermataDiGioco
     */
    public SchermataDiCombattimento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAttacco = new javax.swing.JButton();
        btnDifesa = new javax.swing.JButton();
        btnCaricaKi = new javax.swing.JButton();
        btnSchivata = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnMossaFinale = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 30, 180, 210);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(480, 40, 250, 170);

        btnAttacco.setText("Attacco");
        getContentPane().add(btnAttacco);
        btnAttacco.setBounds(40, 270, 72, 23);

        btnDifesa.setText("Difesa");
        getContentPane().add(btnDifesa);
        btnDifesa.setBounds(180, 270, 72, 23);

        btnCaricaKi.setText("CaricaKi");
        getContentPane().add(btnCaricaKi);
        btnCaricaKi.setBounds(40, 360, 73, 23);

        btnSchivata.setText("Schivata");
        getContentPane().add(btnSchivata);
        btnSchivata.setBounds(180, 360, 74, 23);

        jButton1.setText("MossaFinale");
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 430, 210, 23);

        btnMossaFinale.setText("jLabel3");
        getContentPane().add(btnMossaFinale);
        btnMossaFinale.setBounds(0, 0, 810, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SchermataDiCombattimento().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttacco;
    private javax.swing.JButton btnCaricaKi;
    private javax.swing.JButton btnDifesa;
    private javax.swing.JLabel btnMossaFinale;
    private javax.swing.JButton btnSchivata;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
