/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gdr.dragonball;

/**
 *
 * @author grott
 */
public class SchermataDiCombattimento extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SchermataDiCombattimento.class.getName());
    
    
     /**
     * Creates new form SchermataDiCombattimento
     */
    public SchermataDiCombattimento() {
        initComponents();

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAttacco = new javax.swing.JButton();
        btnDifesa = new javax.swing.JButton();
        btnSchivata = new javax.swing.JButton();
        btnMossaFinale = new javax.swing.JButton();
        lblImmagineNemico1 = new javax.swing.JLabel();
        btnCaricaKi = new javax.swing.JButton();
        CaricaKi2 = new javax.swing.JButton();
        lblImmagineNemico2 = new javax.swing.JLabel();
        lblSfondomappa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnAttacco.setText("jButton1");
        btnAttacco.addActionListener(this::btnAttaccoActionPerformed);
        getContentPane().add(btnAttacco);
        btnAttacco.setBounds(17, 318, 75, 23);

        btnDifesa.setText("jButton1");
        btnDifesa.addActionListener(this::btnDifesaActionPerformed);
        getContentPane().add(btnDifesa);
        btnDifesa.setBounds(138, 318, 75, 23);

        btnSchivata.setText("jButton1");
        btnSchivata.addActionListener(this::btnSchivataActionPerformed);
        getContentPane().add(btnSchivata);
        btnSchivata.setBounds(17, 379, 75, 20);

        btnMossaFinale.setText("jButton1");
        btnMossaFinale.addActionListener(this::btnMossaFinaleActionPerformed);
        getContentPane().add(btnMossaFinale);
        btnMossaFinale.setBounds(80, 440, 75, 23);

        lblImmagineNemico1.setText("jLabel1");
        getContentPane().add(lblImmagineNemico1);
        lblImmagineNemico1.setBounds(0, 0, 190, 250);

        btnCaricaKi.setText("jButton1");
        btnCaricaKi.addActionListener(this::btnCaricaKiActionPerformed);
        getContentPane().add(btnCaricaKi);
        btnCaricaKi.setBounds(138, 376, 75, 23);

        CaricaKi2.setText("jButton1");
        getContentPane().add(CaricaKi2);
        CaricaKi2.setBounds(138, 376, 75, 23);

        lblImmagineNemico2.setText("jLabel1");
        getContentPane().add(lblImmagineNemico2);
        lblImmagineNemico2.setBounds(330, 30, 190, 250);

        lblSfondomappa.setText("jLabel1");
        getContentPane().add(lblSfondomappa);
        lblSfondomappa.setBounds(0, 0, 520, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAttaccoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttaccoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAttaccoActionPerformed

    private void btnDifesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDifesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDifesaActionPerformed

    private void btnSchivataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSchivataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSchivataActionPerformed

    private void btnCaricaKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaricaKiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCaricaKiActionPerformed

    private void btnMossaFinaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMossaFinaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMossaFinaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SchermataDiCombattimento().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CaricaKi2;
    private javax.swing.JButton btnAttacco;
    private javax.swing.JButton btnCaricaKi;
    private javax.swing.JButton btnDifesa;
    private javax.swing.JButton btnMossaFinale;
    private javax.swing.JButton btnSchivata;
    private javax.swing.JLabel lblImmagineNemico1;
    private javax.swing.JLabel lblImmagineNemico2;
    private javax.swing.JLabel lblSfondomappa;
    // End of variables declaration//GEN-END:variables
}
