/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gdr.dragonball;

import javax.swing.*;
import java.util.Random;

/**
 *
 * @author grott
 */
public class SceltaPersonaggio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(schermataMondo.class.getName());
    private JButton[] bottoniPersonaggi; 
    private JLabel[] labelImmagini; 
    private Personaggio personaggioSelezionato; 
    
    private String[] tuttiNomi = {
        "goku_ragazzo", "goku_adulto", "goku_gt", "goku_ultra_istinto", 
        "vegeta_scouter", "vegeta_majin", "baby_vegeta", "vegeta_ultra_ego",
        "gohan_bambino", "gohan_ragazzo", "gohan_mystic", "gohan_beast",
        "trunks_futuro", "trunks_bambino", "xeno_trunks",
        "vegito", "gogeta", "gotenks",
        "freezer", "cooler", "metal_cooler", "broly_anni_90", 
        "broly_super_saiyan_della_leggenda", "janemba", "hildegarn", "cell_max",
        "beerus", "whis", "jiren", "goku_black", "zamasu", "hit",
        "crilin", "yamcha", "tenshinhan", "maestro_muten", "arale",
        "syn_shenron", "uub",
        "moro", "granolah", "gas"
    };

    private int indicePagina = 0; 
    private final int BOTTONI_PER_PAGINA = 6;

    public SceltaPersonaggio() {
        initComponents(); 
        
        bottoniPersonaggi = new JButton[]{jButton1, jButton2, jButton3, jButton4, jButton5, jButton6};
        labelImmagini = new JLabel[]{jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel2};
        
        btnAvvia.setVisible(false);

        for (JButton btn : bottoniPersonaggi) {
            btn.addActionListener(e -> {
                selezionaPersonaggio(btn.getText());
            });
        }

        aggiornaBottoni();
        
        setSize(1000, 400);
        setLocationRelativeTo(null);
    }
    private void impostaCella(int i, String nomeID) {
        if (nomeID != null) {
            bottoniPersonaggi[i].setText(nomeID.replace("_", " "));
            bottoniPersonaggi[i].setVisible(true);

            try {
                String path = "/gdr/dragonball/immagini/" + nomeID + ".png";
                java.net.URL imgURL = getClass().getResource(path);
            
                if (imgURL != null) {
                    ImageIcon icon = new ImageIcon(imgURL);
                    
                    int w = labelImmagini[i].getWidth();
                    int h = labelImmagini[i].getHeight();
                    
                    java.awt.Image img = icon.getImage().getScaledInstance(w, h, java.awt.Image.SCALE_SMOOTH);
                
                    labelImmagini[i].setIcon(new ImageIcon(img));
                    labelImmagini[i].setText(""); 
                } else {
                    labelImmagini[i].setIcon(null);
                    labelImmagini[i].setText("No Img");
                }
            } catch (Exception e) {
                labelImmagini[i].setIcon(null);
            }
            labelImmagini[i].setVisible(true);
        } else {
            bottoniPersonaggi[i].setVisible(false);
            labelImmagini[i].setVisible(false);
        }
    }
    
    private void aggiornaBottoni() {
        for (int i = 0; i < BOTTONI_PER_PAGINA; i++) {
            int indiceReale = indicePagina + i;

            if (indiceReale < tuttiNomi.length) {
                impostaCella(i, tuttiNomi[indiceReale]);
            } else {
                impostaCella(i, null);
            }
        }   

        btnIndietro.setEnabled(indicePagina > 0);
        btnAvanti.setEnabled(indicePagina + BOTTONI_PER_PAGINA < tuttiNomi.length);
    }

    private void selezionaPersonaggio(String nomeVisibile) {
        String nomeID = nomeVisibile.toLowerCase().replace(" ", "_");
        
        personaggioSelezionato = new Personaggio(nomeID);
        
        btnAvvia.setText("Avvia con " + nomeVisibile);
        btnAvvia.setVisible(true);
    }

    private void avviaGioco() {
        if (personaggioSelezionato != null) {

            schermataMondo mondo = new schermataMondo(personaggioSelezionato);
            mondo.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Seleziona un personaggio prima!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnIndietro = new javax.swing.JButton();
        btnAvanti = new javax.swing.JButton();
        btnAvvia = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 300, 180, 60);

        jButton2.setText("jButton2");
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 300, 180, 60);

        jButton3.setText("jButton3");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        getContentPane().add(jButton3);
        jButton3.setBounds(430, 300, 200, 60);

        jButton4.setText("jButton4");
        getContentPane().add(jButton4);
        jButton4.setBounds(660, 300, 210, 60);

        jButton5.setText("jButton5");
        getContentPane().add(jButton5);
        jButton5.setBounds(910, 300, 180, 60);

        jButton6.setText("jButton6");
        getContentPane().add(jButton6);
        jButton6.setBounds(1160, 303, 180, 60);

        btnIndietro.setText("Indietro");
        btnIndietro.addActionListener(this::btnIndietroActionPerformed);
        getContentPane().add(btnIndietro);
        btnIndietro.setBounds(380, 430, 190, 60);

        btnAvanti.setText("Avanti");
        btnAvanti.addActionListener(this::btnAvantiActionPerformed);
        getContentPane().add(btnAvanti);
        btnAvanti.setBounds(660, 430, 210, 60);

        btnAvvia.setText("Avvia");
        btnAvvia.addActionListener(this::btnAvviaActionPerformed);
        getContentPane().add(btnAvvia);
        btnAvvia.setBounds(982, 423, 210, 70);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1160, 70, 180, 230);

        jLabel3.setText("jLabel2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 40, 180, 260);

        jLabel4.setText("jLabel2");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 40, 180, 260);

        jLabel5.setText("jLabel2");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(430, 50, 200, 250);

        jLabel6.setText("jLabel2");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(660, 50, 210, 250);

        jLabel7.setText("jLabel2");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(910, 60, 180, 240);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\grott\\Downloads\\Gemini_Generated_Image_sf6v45sf6v45sf6v.png")); // NOI18N
        jLabel9.setText("jLabel2");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 1370, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnIndietroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndietroActionPerformed
        indicePagina -= BOTTONI_PER_PAGINA;
        if (indicePagina < 0) indicePagina = 0;
        aggiornaBottoni();
    }//GEN-LAST:event_btnIndietroActionPerformed

    private void btnAvantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvantiActionPerformed
        indicePagina += BOTTONI_PER_PAGINA;
        aggiornaBottoni();
    }//GEN-LAST:event_btnAvantiActionPerformed

    private void btnAvviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvviaActionPerformed
        avviaGioco();
    }//GEN-LAST:event_btnAvviaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SceltaPersonaggio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvanti;
    private javax.swing.JButton btnAvvia;
    private javax.swing.JButton btnIndietro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
