/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gdr.dragonball;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author grott
 */
public class schermataMondo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(schermataMondo.class.getName());
    private Personaggio eroe;
    private Inventario mioInventario = new Inventario();
    private boolean nemicoPresente = false;

    public schermataMondo(Personaggio eroe) {
        this.eroe = eroe;
        initComponents();

        caricaImmaginePersonaggio();

        btnCombatti.setVisible(false);
        btnNonCombatti.setVisible(false);

        setSize(800, 600);
        setLocationRelativeTo(null);
        btnCombatti.setContentAreaFilled(false);
        btnEsplora.setContentAreaFilled(false);
        btnInventario.setContentAreaFilled(false);
        btnNonCombatti.setContentAreaFilled(false);
        btnSalvaPartita.setContentAreaFilled(false);
        btnUsaOggetto.setContentAreaFilled(false);
    }

    private void caricaImmaginePersonaggio() {
        String path = "/gdr/dragonball/immagini/" + eroe.id + ".png";

        java.net.URL imgURL = getClass().getResource(path);

        if (imgURL != null) {
            ImageIcon icon = new ImageIcon(imgURL);

            int w = lblPersonaggio.getWidth();
            int h = lblPersonaggio.getHeight();

            java.awt.Image img = icon.getImage().getScaledInstance(w, h, java.awt.Image.SCALE_SMOOTH);

            lblPersonaggio.setIcon(new ImageIcon(img));
            lblPersonaggio.setText("");
        } else {
            lblPersonaggio.setText("Immagine non trovata: " + path); 
        }
    }
    
    public void setInventario(Inventario salvato) {
        this.mioInventario = salvato;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInventario = new javax.swing.JButton();
        btnEsplora = new javax.swing.JButton();
        btnNonCombatti = new javax.swing.JButton();
        lblPersonaggio = new javax.swing.JLabel();
        btnCombatti = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnUsaOggetto = new javax.swing.JButton();
        btnSalvaPartita = new javax.swing.JButton();
        lblPersonaggio1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnInventario.addActionListener(this::btnInventarioActionPerformed);
        getContentPane().add(btnInventario);
        btnInventario.setBounds(60, 580, 160, 50);

        btnEsplora.addActionListener(this::btnEsploraActionPerformed);
        getContentPane().add(btnEsplora);
        btnEsplora.setBounds(300, 580, 160, 40);

        btnNonCombatti.addActionListener(this::btnNonCombattiActionPerformed);
        getContentPane().add(btnNonCombatti);
        btnNonCombatti.setBounds(60, 770, 160, 50);

        lblPersonaggio.setText("jLabel1");
        getContentPane().add(lblPersonaggio);
        lblPersonaggio.setBounds(80, 70, 400, 420);

        btnCombatti.addActionListener(this::btnCombattiActionPerformed);
        getContentPane().add(btnCombatti);
        btnCombatti.setBounds(290, 770, 160, 50);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(590, 0, 630, 560);

        btnUsaOggetto.addActionListener(this::btnUsaOggettoActionPerformed);
        getContentPane().add(btnUsaOggetto);
        btnUsaOggetto.setBounds(180, 670, 160, 40);

        btnSalvaPartita.addActionListener(this::btnSalvaPartitaActionPerformed);
        getContentPane().add(btnSalvaPartita);
        btnSalvaPartita.setBounds(770, 800, 400, 40);

        lblPersonaggio1.setIcon(new javax.swing.ImageIcon("C:\\Users\\grott\\Downloads\\Gemini_Generated_Image_mi4ubemi4ubemi4u.png")); // NOI18N
        lblPersonaggio1.setText("jLabel1");
        getContentPane().add(lblPersonaggio1);
        lblPersonaggio1.setBounds(0, 0, 1220, 860);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 100, 100);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 100, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        jTextArea1.append("--- APERTURA ZAINO ---\n");
        jTextArea1.append(mioInventario.mostraOggetti());
        jTextArea1.append("-----------------------\n");
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnEsploraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsploraActionPerformed
        String evento = GestoreEsplorazione.esplora(mioInventario);

        if (evento.startsWith("OGGETTO:")) {
            jTextArea1.append("Trovato: " + evento.split(":")[1] + "\n");

        } else if (evento.equals("NEMICO")) {
            jTextArea1.append("Nemico apparso!\n");

            nemicoPresente = true;
            btnCombatti.setVisible(true);
            btnNonCombatti.setVisible(true);

        } else {
            jTextArea1.append("Nulla trovato\n");
        }
    }//GEN-LAST:event_btnEsploraActionPerformed

    private void btnNonCombattiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNonCombattiActionPerformed
        jTextArea1.append("Hai evitato il combattimento\n");
        nemicoPresente = false;
        btnCombatti.setVisible(false);
        btnNonCombatti.setVisible(false);
    }//GEN-LAST:event_btnNonCombattiActionPerformed

    private void btnCombattiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCombattiActionPerformed
        CombattimentoStato res = GestoreCombattimento.eseguiCombattimento(eroe);

        jTextArea1.append("Nemico: " + res.nemico.nome + "\n");
        jTextArea1.append(res.messaggio + "\n");

        if (res.vittoria) {
            String drop = mioInventario.dropCasuale();
            jTextArea1.append("Hai trovato: " + drop + "\n");
        }

        nemicoPresente = false;
        btnCombatti.setVisible(false);
        btnNonCombatti.setVisible(false);
    }//GEN-LAST:event_btnCombattiActionPerformed

    private void btnUsaOggettoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsaOggettoActionPerformed
        String nomeOggetto = JOptionPane.showInputDialog(this,"Cosa vuoi usare?\n" + mioInventario.mostraOggetti(),"Usa Oggetto",JOptionPane.QUESTION_MESSAGE);

        if (nomeOggetto == null || nomeOggetto.trim().isEmpty()) {
            return;
        }

        if (mioInventario.rimuoviOggetto(nomeOggetto)) {
            String scelta = nomeOggetto.toLowerCase().trim();

            switch (scelta) {
                case "senzu":
                eroe.hp = 100;
                jTextArea1.append("Hai mangiato un Senzu! HP ripristinati al massimo.\n");
                break;

                case "tuta da combattimento":
                eroe.difesa += 15;
                jTextArea1.append("Hai indossato la Tuta. Difesa +15!\n");
                break;

                case "capsula hoi-poi":
                eroe.attacco += 10;
                jTextArea1.append("La capsula conteneva un'arma! Attacco +10.\n");
                break;

                case "acqua miracolosa":
                eroe.attacco += 20;
                eroe.hp -= 10;
                jTextArea1.append("Hai bevuto l'Acqua Miracolosa! Attacco aumentato drasticamente, ma ti senti spossato.\n");
                break;

                case "scouter":
                eroe.attacco += 5;
                eroe.difesa += 5;
                jTextArea1.append("Hai attivato lo Scouter! Ora vedi i punti deboli del nemico.\n");
                break;

                case "z-sword":
                eroe.attacco += 40;
                jTextArea1.append("Impugni la leggendaria Spada Z! La tua forza è ora immensa.\n");
                break;

                case "pesetto da 100 tonnellate":
                eroe.difesa += 30;
                jTextArea1.append("Ti sei allenato con i pesi di Re Kaioh. Difesa aumentata!\n");
                break;

                case "bastone nyoi":
                eroe.attacco += 12;
                jTextArea1.append("Il Bastone Nyoi si allunga! Colpisci da lontano: Attacco +12.\n");
                break;

                case "pozione di re magno":
                eroe.hp += 50;
                if(eroe.hp > 100) eroe.hp = 100;
                jTextArea1.append("Hai bevuto la Pozione. Hai recuperato 50 HP.\n");
                break;

                default:
                jTextArea1.append("Hai usato " + nomeOggetto + ", ma non ne capisci l'utilità.\n");
                break;
            }
        }else {
            JOptionPane.showMessageDialog(this, "Non hai questo oggetto nell'inventario!", "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUsaOggettoActionPerformed

    private void btnSalvaPartitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaPartitaActionPerformed
        try {

            java.io.FileOutputStream fileOut = new java.io.FileOutputStream("salvataggio.dat");
            java.io.ObjectOutputStream out = new java.io.ObjectOutputStream(fileOut);

            out.writeObject(eroe);
            out.writeObject(mioInventario);

            out.close();
            fileOut.close();

            JOptionPane.showMessageDialog(this, "Partita salvata con successo!", "Salvataggio", JOptionPane.INFORMATION_MESSAGE);
            jTextArea1.append(">>> Progressi salvati nel file 'salvataggio.dat'\n");

        } catch (java.io.IOException i) {
            i.printStackTrace();
            JOptionPane.showMessageDialog(this, "Errore durante il salvataggio!", "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvaPartitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new schermataMondo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCombatti;
    private javax.swing.JButton btnEsplora;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnNonCombatti;
    private javax.swing.JButton btnSalvaPartita;
    private javax.swing.JButton btnUsaOggetto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblPersonaggio;
    private javax.swing.JLabel lblPersonaggio1;
    // End of variables declaration//GEN-END:variables
}
